# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/feixiao/workspace/ivoldual/ivoldual

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/feixiao/workspace/ivoldual/ivoldual

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feixiao/workspace/ivoldual/ivoldual/CMakeFiles /home/feixiao/workspace/ivoldual/ivoldual/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feixiao/workspace/ivoldual/ivoldual/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named ivoldual

# Build rule for target.
ivoldual: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ivoldual
.PHONY : ivoldual

# fast build rule for target.
ivoldual/fast:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/build
.PHONY : ivoldual/fast

#=============================================================================
# Target rules for targets named tar

# Build rule for target.
tar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tar
.PHONY : tar

# fast build rule for target.
tar/fast:
	$(MAKE) -f CMakeFiles/tar.dir/build.make CMakeFiles/tar.dir/build
.PHONY : tar/fast

ijkdual_datastruct.o: ijkdual_datastruct.cxx.o
.PHONY : ijkdual_datastruct.o

# target to build an object file
ijkdual_datastruct.cxx.o:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ijkdual_datastruct.cxx.o
.PHONY : ijkdual_datastruct.cxx.o

ijkdual_datastruct.i: ijkdual_datastruct.cxx.i
.PHONY : ijkdual_datastruct.i

# target to preprocess a source file
ijkdual_datastruct.cxx.i:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ijkdual_datastruct.cxx.i
.PHONY : ijkdual_datastruct.cxx.i

ijkdual_datastruct.s: ijkdual_datastruct.cxx.s
.PHONY : ijkdual_datastruct.s

# target to generate assembly for a file
ijkdual_datastruct.cxx.s:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ijkdual_datastruct.cxx.s
.PHONY : ijkdual_datastruct.cxx.s

isodual.o: isodual.cxx.o
.PHONY : isodual.o

# target to build an object file
isodual.cxx.o:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/isodual.cxx.o
.PHONY : isodual.cxx.o

isodual.i: isodual.cxx.i
.PHONY : isodual.i

# target to preprocess a source file
isodual.cxx.i:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/isodual.cxx.i
.PHONY : isodual.cxx.i

isodual.s: isodual.cxx.s
.PHONY : isodual.s

# target to generate assembly for a file
isodual.cxx.s:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/isodual.cxx.s
.PHONY : isodual.cxx.s

ivoldual.o: ivoldual.cxx.o
.PHONY : ivoldual.o

# target to build an object file
ivoldual.cxx.o:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual.cxx.o
.PHONY : ivoldual.cxx.o

ivoldual.i: ivoldual.cxx.i
.PHONY : ivoldual.i

# target to preprocess a source file
ivoldual.cxx.i:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual.cxx.i
.PHONY : ivoldual.cxx.i

ivoldual.s: ivoldual.cxx.s
.PHONY : ivoldual.s

# target to generate assembly for a file
ivoldual.cxx.s:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual.cxx.s
.PHONY : ivoldual.cxx.s

ivoldualIO.o: ivoldualIO.cxx.o
.PHONY : ivoldualIO.o

# target to build an object file
ivoldualIO.cxx.o:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldualIO.cxx.o
.PHONY : ivoldualIO.cxx.o

ivoldualIO.i: ivoldualIO.cxx.i
.PHONY : ivoldualIO.i

# target to preprocess a source file
ivoldualIO.cxx.i:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldualIO.cxx.i
.PHONY : ivoldualIO.cxx.i

ivoldualIO.s: ivoldualIO.cxx.s
.PHONY : ivoldualIO.s

# target to generate assembly for a file
ivoldualIO.cxx.s:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldualIO.cxx.s
.PHONY : ivoldualIO.cxx.s

ivoldual_datastruct.o: ivoldual_datastruct.cxx.o
.PHONY : ivoldual_datastruct.o

# target to build an object file
ivoldual_datastruct.cxx.o:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_datastruct.cxx.o
.PHONY : ivoldual_datastruct.cxx.o

ivoldual_datastruct.i: ivoldual_datastruct.cxx.i
.PHONY : ivoldual_datastruct.i

# target to preprocess a source file
ivoldual_datastruct.cxx.i:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_datastruct.cxx.i
.PHONY : ivoldual_datastruct.cxx.i

ivoldual_datastruct.s: ivoldual_datastruct.cxx.s
.PHONY : ivoldual_datastruct.s

# target to generate assembly for a file
ivoldual_datastruct.cxx.s:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_datastruct.cxx.s
.PHONY : ivoldual_datastruct.cxx.s

ivoldual_main.o: ivoldual_main.cxx.o
.PHONY : ivoldual_main.o

# target to build an object file
ivoldual_main.cxx.o:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_main.cxx.o
.PHONY : ivoldual_main.cxx.o

ivoldual_main.i: ivoldual_main.cxx.i
.PHONY : ivoldual_main.i

# target to preprocess a source file
ivoldual_main.cxx.i:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_main.cxx.i
.PHONY : ivoldual_main.cxx.i

ivoldual_main.s: ivoldual_main.cxx.s
.PHONY : ivoldual_main.s

# target to generate assembly for a file
ivoldual_main.cxx.s:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_main.cxx.s
.PHONY : ivoldual_main.cxx.s

ivoldual_triangulate.o: ivoldual_triangulate.cxx.o
.PHONY : ivoldual_triangulate.o

# target to build an object file
ivoldual_triangulate.cxx.o:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_triangulate.cxx.o
.PHONY : ivoldual_triangulate.cxx.o

ivoldual_triangulate.i: ivoldual_triangulate.cxx.i
.PHONY : ivoldual_triangulate.i

# target to preprocess a source file
ivoldual_triangulate.cxx.i:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_triangulate.cxx.i
.PHONY : ivoldual_triangulate.cxx.i

ivoldual_triangulate.s: ivoldual_triangulate.cxx.s
.PHONY : ivoldual_triangulate.s

# target to generate assembly for a file
ivoldual_triangulate.cxx.s:
	$(MAKE) -f CMakeFiles/ivoldual.dir/build.make CMakeFiles/ivoldual.dir/ivoldual_triangulate.cxx.s
.PHONY : ivoldual_triangulate.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... tar"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... ivoldual"
	@echo "... ijkdual_datastruct.o"
	@echo "... ijkdual_datastruct.i"
	@echo "... ijkdual_datastruct.s"
	@echo "... isodual.o"
	@echo "... isodual.i"
	@echo "... isodual.s"
	@echo "... ivoldual.o"
	@echo "... ivoldual.i"
	@echo "... ivoldual.s"
	@echo "... ivoldualIO.o"
	@echo "... ivoldualIO.i"
	@echo "... ivoldualIO.s"
	@echo "... ivoldual_datastruct.o"
	@echo "... ivoldual_datastruct.i"
	@echo "... ivoldual_datastruct.s"
	@echo "... ivoldual_main.o"
	@echo "... ivoldual_main.i"
	@echo "... ivoldual_main.s"
	@echo "... ivoldual_triangulate.o"
	@echo "... ivoldual_triangulate.i"
	@echo "... ivoldual_triangulate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

